### ISSUE TITLE
Register CDB1GlobalGrid TileMatrixSet

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#106]
https://docs.opengeospatial.org/DRAFTS/17-083r4.html#cdb1-global-grid-tilematrixset-definition

[CDB1GlobalGrid.json](https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/schemas/tms/2.0/json/examples/tilematrixset/CDB1GlobalGrid.json)
[CDB1GlobalGrid.xml](https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/schemas/tms/2.0/xml/examples/tilematrixset/CDB1GlobalGrid.xml)

**Comment by ghobona** [comment]
2021-06-17 OGC-NA this issue will be put on hold until the 2D TMS v2.0 standard is approved.

**Comment by jerstlouis** [comment]
The Tiles SWG has set up a TileMatrixSet registry holding all definitions of registered TileMatrixSet at https://github.com/opengeospatial/2D-Tile-Matrix-Set/tree/master/registry/, including both JSON and XML encodings, with the intent that the OGC definition server could return the content of those definitions directly based on content negotiation.

Note that these follow the logical model and encodings defined in 2DTMS 2.0.
The TileMatrixSet identifiers for these howeverr should still maintain the `http://www.opengis.net/def/tilematrixset/OGC/1.0/`  (**1.**0) identifier part, as the conceptual definition for these tile matrix sets themselves did not change (and should never need to change) since 2DTMS 1.0. Unversioned identifiers could also be used (as discussed in #143), and would probably be preferable.
