### ISSUE TITLE
Extend URI syntax to support 

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/NamingAuthority#107]
The http URI string http://www.opengis.net/def/objectType/authority/version/code defined in N/A document 09-048 does not permit a user to request the definition returned to be in a desired encoding.

Can N/A extend this syntax with an optional mechanism for requesting definitions in GML, WKT [conformant to 18-010], JSON, etc. Registries will vary in their support for particular encodings, but some can serve definitions in one of several encodings.

**Comment by dr-shorthair** [comment]
Content negotiation - @rob-metalinkage @nicholascar

**Comment by rob-metalinkage** [comment]
Mechanisms are no problem - we support two ..

but why doesnt this URI appear in the definitions server (i.e. why is it not in the content in this repo which gets loaded to the definitions server?)

We would need also either the canonical versions in WKT, GML etc or some python code to generate these we could incorporate into the definitions server infrastructure for dynamic views, or into pre-processing workflows ( we are loing into setting up github hooks to preprocess content on update  ...)

**Comment by ghobona** [comment]
@rob-metalinkage The URI does not exist in the Definitions Server.

**Comment by ghobona** [comment]
PR https://github.com/opengeospatial/NamingAuthority/pull/127 merged.
