### ISSUE TITLE
Registration of GeoTIFF MIME type

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#11]
The GeoTIFF SWG has requested that the OGC-NA register the GeoTIFF MIME type with IANA.

**Comment by ghobona** [comment]
@ogcscotts has accepted the task.

**Comment by nicholascar** [comment]
@ogcscott, there is an IANA form for this: https://www.iana.org/form/media-types

**Comment by ogcscotts** [comment]
see GeoTIFF Issue here: https://github.com/opengeospatial/geotiff/issues/34

we need to decide if a completely new media type is desired.

**Comment by ghobona** [comment]
https://github.com/opengeospatial/geotiff/issues/34#issuecomment-770897766

**Comment by ghobona** [comment]
Closing this ticket because the conclusion of the discussion at https://github.com/opengeospatial/geotiff/issues/34 was that `image/tiff; application=geotiff` can be used without the need to register a new media type at IANA.
