### ISSUE TITLE
sameAs and alternative forms of URIs 

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/NamingAuthority#116]
Some of the content provided for the Definition Server has the following pattern..

<http://www.opengis.net/def/observation-type>
	owl:sameAs <http://www.opengis.net/def/observationType> ;
.

<http://www.opengis.net/def/observationType>
	rdf:type skos:ConceptScheme ;

like this, only the <http://www.opengis.net/def/observationType>  URI resolves properly.

The Naming Authority can entail copies of all the properties for both forms of URI, and create inverse sameAs  relationships.

This is probably the first priority... but.....

sameAs implies equal status of both identifiers - is this really going to be true?  

In the short term we will expose content this way, but really SWGs need to review  the requirements here.

**Comment by ghobona** [comment]
Related to https://github.com/opengeospatial/NamingAuthority/issues/121

**Comment by ghobona** [comment]
The draft text addressing this issue is at https://github.com/opengeospatial/NamingAuthority/blob/fix_for_issue_120/policyAndProcedures/OGCNANameTypeSpecificationForDefinitions/clause_7_subclause_alias.adoc

If there are any objections or requests for changes to the text, please post a comment in this Issue by 2021-12-31.

**Comment by ghobona** [comment]
The fix has been moved to the master branch.

An HTML version of the policy document will be generated once [metanorma Issue 369](https://github.com/metanorma/metanorma-ogc/issues/369) has been fixed.

**Comment by ghobona** [comment]
Draft Policy revision sent to OGC-NA for review. This issue is addressed in [Clause 6.7](https://portal.ogc.org/files/?artifact_id=100119#toc22)

**Comment by ghobona** [comment]
The [revised policy](https://docs.opengeospatial.org/pol/09-048r6.html#toc22) has been published.
