### ISSUE TITLE
The WFS SWG has requested for registration of CRS84h

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#12]
CRS84h is a version of the CRS:84 coordinate system, with an additional axis for height. The WFS SWG has requested that it be registered. 
The CRS DWG has reviewed the proposal and endorsed it  at Leuven TC.

**Comment by dr-shorthair** [comment]
Height ??!!!? Do they mean 'elevation'. 

My height is 1.76m. 
My current elevation is ca. 70m above MSL. 

(And please don't say 'altitude', which is distance above the non-gaseous surface.)
