### ISSUE TITLE
Register http://www.opengis.net/def/crs/OGC/0/CRS84 as an alias of http://www.opengis.net/def/crs/OGC/1.3/CRS84

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#120]
Can we also register http://www.opengis.net/def/crs/OGC/0/CRS84 as an alias for http://www.opengis.net/def/crs/OGC/1.3/CRS84 so that OGC:CRS84 can be used, too?

Proposal original at made at https://github.com/opengeospatial/NamingAuthority/issues/92#issuecomment-869396150

**Comment by rob-metalinkage** [comment]
We also need some content rules to go with this - what is the definitions server supposed to do with aliases in general? 
I have added #121  for this more general discussion.

**Comment by ghobona** [comment]
This proposal will be discussed during the OGC-NA session on September 14th, 2021.

**Comment by cportele** [comment]
Background and discussion:

* There is the proposal to support compact URIs including `[epsg:4326]` or `[ogc-rel:conformance]` using CURIEs (see https://github.com/opengeospatial/NamingAuthority/issues/92#issuecomment-888186821).
* There is an implicit assumption in the proposal that for each registered resource (at least for certain resource types like `crs` or `rel`) there is a version `0` for the resource.
* This, however, is currently not the case. For example, `http://www.opengis.net/def/crs/OGC/1.3/CRS84` includes a version "1.3" based on the WMS version when the identifier was introduced (although that fact cannot be represented and it is lost). All OGC link relation types use a version "1.0". The version information may be useful in some circumstances, but for most resources and most uses it is not relevant.
* There should be a general rule that version "0" can be used for all resources as an alias to the lastest version of the resource. This would address this request, simplify the use of OGC definition server URIs in general and be a pre-condition for the use of CURIEs.

**Comment by ghobona** [comment]
OGC-NA agreed on 2021-09-14 to look into whether a policy revision that applies the rule across all object types is possible and whether it would adversely affect any other object types.

**Comment by ghobona** [comment]
The draft policy update is referenced at https://github.com/opengeospatial/NamingAuthority/issues/116#issuecomment-985453177

Once the policy update is approved, we can then register http://www.opengis.net/def/crs/OGC/0/CRS84 as an alias of http://www.opengis.net/def/crs/OGC/1.3/CRS84

**Comment by nmtoken** [comment]
Perhaps should also register:

http://www.opengis.net/def/crs/OGC/0/LonLat84_5773

as an alias.

From https://docs.opengeospatial.org/is/12-007r2/12-007r2.html 
_Annex B: KML Coordinate Reference System Definition (Normative)_

**Comment by ghobona** [comment]
http://www.opengis.net/def/crs/OGC/0/CRS84 has been enabled as an alias of http://www.opengis.net/def/crs/OGC/1.3/CRS84
