### ISSUE TITLE
missing Content

### ISSUE THREAD

**Issue by marqh** [opengeospatial/NamingAuthority#122]
hello Naming Authority

#87 addressed some issues of missing content for the Binary Array linked data vocabulary
(thank you)

in running some tests, it has become apparent that this is only a partial fix

The `owl:Class' instances such as:
* https://www.opengis.net/def/binary-array-ld/Array
are resolving
however other resource types, such as:
* `owl:DatatypeProperty`, e.g.:
    * https://www.opengis.net/def/binary-array-ld/sourceRefShape
* `owl:ObjectProperty`, e.g.:
    * https://www.opengis.net/def/binary-array-ld/isPrefixedBy

are returning 
```
Input Error
Status
    400
Message
    The object with URI https://www.opengis.net/def/binary-array-ld/isPrefixedBy is not of type skos:ConceptScheme, skos:Collection or skos:Concept and only these classes of object are understood by VocPrez
```
which means that tests expecting a 200 code to indicate known publishing of these terms are returning failure

What is different about these different types that means that some entities within the ontology are being published as known resources and others are not (seemingly based on the resource type definition)?

Is this something that can be fixed for us?

many thanks
mark

**Comment by rob-metalinkage** [comment]
This took a while - finally got to the stage where safe to publish to production using the automation scripts.
