### ISSUE TITLE
legacy redirect

### ISSUE THREAD

**Issue by marqh** [opengeospatial/NamingAuthority#123]
Hello Naming Authority

https://www.opengis.net/def/binary-array-ld

is currently resolving via a hard coded redirect to 

https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/binary-array-ld/binary-array-ld.ttl

This was set up some time ago as an interim measure to ensure that this ontology was able to be downloaded in full

I think that the 
http://defs.opengis.net/vocprez/object
service has content negotiation capability available

Will it be possible to update the resolution of the 
https://www.opengis.net/def/binary-array-ld
resource such that it routes to an OGC definition page for human browsers, but also supports direct download of the entire ontology as an RDF payload under content negotiation.

i would like to be able to pass 
`Accept: text/turtle` 
to a request for
https://www.opengis.net/def/binary-array-ld

and receive exactly the payload being served from
https://raw.githubusercontent.com/opengeospatial/NamingAuthority/master/incubation/binary-array-ld/binary-array-ld.ttl

without the need for a redirect into the NamingAuthority github master branch

many thanks
mark

**Comment by rob-metalinkage** [comment]
Hi,

This is probably the problem with github - it breaks the MIME types by forcing everything to "text/plain; charset=utf-8" 

so - agree that redirecting to the github with an incorrect MIME type is a violation of HTTP architecture and needs fixing.

I can set up the redirect to  a better resource location with (note we won't arbitrarily proxy content which might be coming from an environment we dont control) - it will always be a redirect - but any HTTP client should handle this properly.  

I've set up a prototype for "direct" access to resources using the correct MIME types ... 
http://defs-dev.opengis.net/ogc-na/incubation/binary-array-ld/binary-array-ld.ttl

I'll need to disable the hardcoded redirect from the OGC and let it fall through to the def server infrastructure... so need to test the more flexible form of redirect rules needed there.

**Comment by dr-shorthair** [comment]
Try https://raw.githack.com/

**Comment by rob-metalinkage** [comment]
@dr-shorthair - have done in the past but they ask you not to use for production ... so we'll need to host our own

**Comment by dr-shorthair** [comment]
They ask you to use https://rawcdn.githack.com for production, and https://raw.githack.com/ for dev work.

**Comment by rob-metalinkage** [comment]
do we need to make a policy decision here?  "but if you need to serve files that are crucial to your business, you should probably pay for a host with well-funded infrastructure and uptime guarantees."

from the perspective of users they need to understand the redirected location is _not_ immutable so this is a good debate to have.. @ghobona can you make a call if this is an internal decision or one for the membership?

**Comment by marqh** [comment]
I'm cautious to avoid talking at cross purposes here.

I'd like to focus on expected behaviour from the naming authority in normal operations.

Specifically if I am interested in requests such as:

```
wget --header 'Accept:text/ttl' -O bald.ttl https://www.opengis.net/def/binary-array-ld
```
* currently returns turtle encoded Owl Ontology
    * please keep this behaviour, we require this ontology as parsable content
    * but, it currently returns this direct from github master, which is unusual
```
wget --header 'Accept:text/html' -O bald.html https://www.opengis.net/def/binary-array-ld
```    
* currently this returns a turtle encoded ontology
* i think this should return a html page from the Naming authority, as would be consumed by a browser / browsing human

I think this is a functionality request, slightly independent from expectation management on 
> if you need to serve files that are crucial to your business

**Comment by ghobona** [comment]
@marqh Content Negotiation through the Accept Header is something that we would like to support. We use 3rd Party open source software for building the Definitions Server. Where a capability is not already supported by the 3rd Party software, it takes time to implement the capability into the Definitions Server. Please bear with us.

@rob-metalinkage Let's discuss offline with the Infrastructure Office (@kstegemoller) how the enhancement could be implemented.

**Comment by rob-metalinkage** [comment]
Yes - we need the HTML rendering and to remove the hack redirect and allow full content negotiation to take place.  I'll work on the HTML rendering now we have upgraded the UI then we can implement the negotiation.

**Comment by marqh** [comment]
hello @ghobona @rob-metalinkage 

thank you for the feedback comments and insights

I understand there are limitations and i would like to be helpful working within them.

I do wonder whether it would be worthwhile to consider the 3 open issues i have raised as a set, and look at the order of work.

it seems to me that ensuring that the content negotiation is working for existing resources would be a valuable step to take prior to making any changes to the redirect (Rob implied this in their previous comment)
It would also be helpful to ensure that the  missing content for the binary-array-ld ontology is being served.

this suggest to me that 
* [ ] #124 
* [ ] #122 
should both be completed prior to addressing this issue.

The legacy redirect is functional for now, ensuring that the majority of work on the standard that this Ontology supports can continue.  given your feedback I'd be comfortable in leaving it in place until #122 and #124 are resolved

many thanks
mark

**Comment by ghobona** [comment]
Discussion on this topic is continuing at https://github.com/opengeospatial/NamingAuthority/issues/123
