### ISSUE TITLE
Remove 'Vocabularies' link from Menu

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#141]
The  'Vocabularies' link returns the complete list of all registered items. Although it allows paging, it's difficult to navigate and gives users the impression that the Definitions Server is difficult to use too. A case in point is the postscript (PS) on the comment https://github.com/opengeospatial/NamingAuthority/issues/138#issuecomment-937717673 .

The Search page is easier to use and presents results in a more user friendly way.

The ConceptScheme Hierarchy under the ‘System Home’ page is also easier to use and presents results in a more user friendly way.

So users do not need the  'Vocabularies' link on the Menu.  Please remove it.

**Comment by ErikStubkjaer41** [comment]
@ghobona 'So users do not need the 'Vocabularies' link on the Menu. Please remove it.'

Frankly, I wonder whether this is worth the effort. 

The ConceptScheme Hierarchy is shorter at the outset, but extending it, you meet a number of duplicates ( Document elements; OGC document types register; Specification elements ),
some holding information on intended work (http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/doc-element/). Not user friendly.

The first item of the ConceptScheme Hierarchy: 'definitions identified by OGC URIs' anyway leads to the 'Vocabularies' page, with the PipelineML mess

A critical review/ editing of the content of the lists/hierarchies seems a first priority.
The structuring of content seems largely taken from an OGC-NA point of view. A more user friendly structuring is needed as well

**Comment by rob-metalinkage** [comment]
User friendliness is indeed an important goal - and needs a more complete User Experience (UX) as well as design and implementation approach than has been possible with part time resources with other project goals.   So thanks first for sharing thoughts about improvements. I will make sure I run a detailed session for stakeholders next TC where we can explore some user perspectives, needs and design ideas.  I will make myself available for a "doctors surgery" each TC to answer questions, show progress etc.  (a 10 min report to the NA each TC is clearly insufficient).

In the meantime I will reach out to Kathi and explore a couple of options to see how well they work.

**Comment by rob-metalinkage** [comment]
The vocabularies list provides a filter option - probably better to leave that until a better search is available. Suggest we defer this till a decent amount of resource can be committed to Ux.

**Comment by ghobona** [comment]
The Vocabularies menu item has now been moved further to the right and re-labelled 'Browse Vocabularies'..

The modification addresses the usability concerns I previously had.

@rob-metalinkage Thanks for the modification. I'm happy with this change, so am closing the GitHub Issue.
