### ISSUE TITLE
Register minimal SELFIE ontologies as "experimental"?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/NamingAuthority#16]
@sgrellet opened: https://github.com/opengeospatial/SELFIE/issues/67 asking about how to get IE-created resources published as "experimental". 

The current HY_Features content is deployed as "proposed", ([e.g. here](https://www.opengis.net/def/appschema/hy_features/hyf/HY_CatchmentArea)) which is accurate since the SWG proposed the content. In this next round, we have not worked directly with the SWGs, yet. 

Should we 1) work with SWGs and have the ontologies route through them? or 2) can the updated ontologies from SELFIE be posted as "experimental"?

Thanks!!

**Comment by ghobona** [comment]
The preferred route is (1). An e-mail vote or portal project vote within the SWG/DWG would suffice. This can be done ahead of a TC meeting or during the next TC meeting.

**Comment by dblodgett-usgs** [comment]
Thanks @ghobona -- we'll initiate email votes to deploy these as "proposed" as we want to evaluate them prior to saying this is totally firm. That seem ok?

**Comment by ghobona** [comment]
Yes, that's fine. Thanks.

**Comment by ghobona** [comment]
Some recent examples of motions.

Please see Slide 5 of the Closing Report of the NetCDF SWG (Banff TC) for an example of an appropriate motion

https://portal.opengeospatial.org/files/?artifact_id=90206

Please see  Slide 7 of the Closing Report of the LandInfra DWG/SWG (Banff TC) for another example of appropriate motion

https://portal.opengeospatial.org/files/?artifact_id=90130

**Comment by dblodgett-usgs** [comment]
@ghobona and @rob-metalinkage's -- based on recent comments in https://github.com/opengeospatial/SELFIE/issues/67, should we consider "experimental" on defs-dev or go ahead and pursue a motion?

**Comment by ghobona** [comment]
@dblodgett-usgs Ok, please proceed with "experimental". Then when the ontology is completed, please submit the ontology to the SWG/DWG for approval.

**Comment by dblodgett-usgs** [comment]
OK. Thanks. Will Do.
