### ISSUE TITLE
Register link relation types for 2DTMS 2.0 & OGC API - Tiles

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#167]
The following OGC link relation types are defined by [_Two-Dimensional Tile Matrix Set & Tileset Metadata 2.0_](https://docs.opengeospatial.org/DRAFTS/17-083r4.html):

- http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme (to link to the definition a of Tile Matrix Set)
- http://www.opengis.net/def/rel/ogc/1.0/geodata (to link to an OGC API collection resource)
- http://www.opengis.net/def/rel/ogc/1.0/dataset (to link to an OGC API dataset landing page)

(https://github.com/opengeospatial/2D-Tile-Matrix-Set/issues/53)

The following additional OGC link relation types are defined by [_OGC API - Tiles - Part 1: Core_](http://docs.ogc.org/DRAFTS/20-057.html):

- http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector (to link to a list of vector tilesets)
- http://www.opengis.net/def/rel/ogc/1.0/tilesets-map (to link to a list of map tilesets)
- http://www.opengis.net/def/rel/ogc/1.0/tilesets-coverage (to link to a list of coverage tilesets)
- http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes (to link to a list of tile matrix sets supported by the API)

(https://github.com/opengeospatial/ogcapi-tiles/issues/40)

**Comment by ghobona** [comment]
Add the following IANA ones as well (used by OGC API - Processes):

- status
- up

**Comment by ghobona** [comment]
This link relation type is mentioned in Requirement 16 of OGC API - Tiles  - Part 1 in relations to maps. It is therefore expected that it will be specified in OGC API - Maps - Part 1. In the meantime, we will proceed to register it so that implementers are aware of it.

http://www.opengis.net/def/rel/ogc/1.0/map
