### ISSUE TITLE
Add second time scale, BP, as agreed in Banff

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/NamingAuthority#17]
@ghobona, @dr-shorthair 
The motion by the Temporal DWG in the OGC TC Banff meeting recommended both time scales (MYA and BP) be added to the OGC Registry.

BP, Before Present, has a datum of 1950 CE and is more appropriate for carbon dating and timescales of simialr accuracy, rather than the traditional Mya geological timescale.

Here is my attempt at some GML:
<TemporalCRS gml:id="before-present-time-crs">
<description>
Concrete temporal CRS of years elapsed from the present, positive backwards.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">
http://www.opengis.net/def/crs/OGC/0/BeforePresentTime
</identifier>
<name>Before Present Time</name>
<remarks>Initial version (0.1)</remarks>
<scope>not known</scope>
<timeCS>
<TimeCS gml:id="before-present-time-crs_a-cs">
<description>
1D coordinate system containing a time axis measuring (Julian) years [a], backwards in time.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%a:cs%</identifier>
<remarks>Initial version (0.1)</remarks>
<axis>
<CoordinateSystemAxis gml:id="before-present-time-crs_a:cs_bp-a" uom="http://www.opengis.net/def/uom/UCUM/0/a">
<description>
Coordinate system axis for the recording of years before the present [BP], backwards in time. 'Present' is defined as 1950 CE. 
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%bp-a%</identifier>
<remarks>Initial version (0.1)</remarks>
<axisAbbrev>years BP</axisAbbrev>
<axisDirection codeSpace="http://www.ietf.org/rfc/rfc3986">
http://www.opengis.net/def/axisDirection/OGC/1.0/past
</axisDirection>
</CoordinateSystemAxis>
</axis>
</TimeCS>
</timeCS>
<temporalDatum>
<TemporalDatum gml:id="before-present-time-crs_yz-td">
<description>
The year 1950 in the Gregorian calendar.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%yz-td%</identifier>
<remarks>
'Present' is defined as 1950 CE, when the first radio carbon dating was done and before the atmosphere was polluted by nuclear fallout.
</remarks>
<scope>not known</scope>
<origin>1950-01-01T00:00:00Z</origin>
</TemporalDatum>
</temporalDatum>
</TemporalCRS>

**Comment by ghobona** [comment]
@chris-little Please resend the post, with the XML inside a code block.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by chris-little** [comment]
@ghobona here is my next attempt:

```
<TemporalCRS gml:id="before-present-time-crs">
<description>
Concrete temporal CRS of years elapsed from the present, positive backwards.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">
http://www.opengis.net/def/crs/OGC/0/BeforePresentTime
</identifier>
<name>Before Present Time</name>
<remarks>Initial version (0.1)</remarks>
<scope>not known</scope>
<timeCS>
<TimeCS gml:id="before-present-time-crs_a-cs">
<description>
1D coordinate system containing a time axis measuring (Julian) years [a], backwards in time.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%a:cs%</identifier>
<remarks>Initial version (0.1)</remarks>
<axis>
<CoordinateSystemAxis gml:id="before-present-time-crs_a:cs_bp-a" uom="http://www.opengis.net/def/uom/UCUM/0/a">
<description>
Coordinate system axis for the recording of years before the present [BP], backwards in time. 'Present' is defined as 1950 CE. 
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%bp-a%</identifier>
<remarks>Initial version (0.1)</remarks>
<axisAbbrev>years BP</axisAbbrev>
<axisDirection codeSpace="http://www.ietf.org/rfc/rfc3986">
http://www.opengis.net/def/axisDirection/OGC/1.0/past
</axisDirection>
</CoordinateSystemAxis>
</axis>
</TimeCS>
</timeCS>
<temporalDatum>
<TemporalDatum gml:id="before-present-time-crs_yz-td">
<description>
The year 1950 in the Gregorian calendar.
</description>
<identifier codeSpace="http://www.ietf.org/rfc/rfc3986">%yz-td%</identifier>
<remarks>
'Present' is defined as 1950 CE, when the first radio carbon dating was done and before the atmosphere was polluted by nuclear fallout.
</remarks>
<scope>not known</scope>
<origin>1950-01-01T00:00:00Z</origin>
```

**Comment by ghobona** [comment]
@pebau Please add [this definition](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/temporal/OGC_0_BeforePresentTime.md) to the CRS Resolver at http://www.opengis.net/def/crs/OGC/0/BeforePresentTime

**Comment by ghobona** [comment]
Thanks @pebau !
