### ISSUE TITLE
Ready for OGC-NA Review: GeoPackage Conceptual and Logical Model

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#176]
OGC-NA,

The document(s) titled "GeoPackage Conceptual and Logical Model" with reference number 21-053 is/are now available for review by the OGC Naming Authority (OGC-NA) Subcommittee.

https://portal.ogc.org/files/?artifact_id=98511&version=1 (OGC Member access only)

Please review the documents by 22:00 UTC on Apr 26, 2022 focusing on its conformance to OGC-NA policies.

OGC-NA policies can be found at https://www.ogc.org/standards/na

The most relevant policies are:

- OGC-NA Name type specification - definitions (09-048r5)
- OGC-NA Name type specification - specification elements (10-103r1)

**Comment by ghobona** [comment]
Comments are in an annotated copy of the document at https://portal.ogc.org/files/?artifact_id=100807

**Comment by jyutzler** [comment]
https://github.com/opengeospatial/geopackage/issues/617#issuecomment-1110986421
