### ISSUE TITLE
Register http://www.opengis.net/def/crs/OGC/0/LonLat84_5773

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#179]
This CRS is specified in [Annex B](https://docs.opengeospatial.org/is/12-007r2/12-007r2.html#kml_crs_def) of the OGC KML 2.3 standard.

Thanks @nmtoken for pointing it out.

@pebau The CRS does not appear to be currently registered in SECORE. Since OGC KML 2.3 is an approved standard, could you please proceed to publish the definition through the SECORE?

**Comment by ghobona** [comment]
@pebau Any progress publishing this definition on SECORE?

**Comment by pebau** [comment]
@ghobona will check and come back asap

**Comment by pebau** [comment]
@ghobona done now, see http://www.opengis.net/def/crs/OGC/0/CRS84

**Comment by dr-shorthair** [comment]
XML ... :dizzy_face: :tired_face:
Any plans to produce a JSON implementation?

**Comment by pebau** [comment]
yes, on the radar since long. The SECORE code is open source, so 2 ways as usual:
- someone enhances the code (we're happy to assist)
- contract to us

**Comment by ghobona** [comment]
@pebau As stated in the title of this GitHub Issue, the request was to register http://www.opengis.net/def/crs/OGC/0/LonLat84_5773  and not http://www.opengis.net/def/crs/OGC/0/CRS84.

Please register http://www.opengis.net/def/crs/OGC/0/LonLat84_5773

**Comment by ghobona** [comment]
@dr-shorthair The CRS SWG is discussing the possibility of a JSON encoding on the [mailing list](https://lists.ogc.org/mailman/private/crs.swg/2022-June/thread.html). OGC Members can access and participate in the discussion after signing the Observer Agreement.

**Comment by pebau** [comment]
> @pebau As stated in the title of this GitHub Issue, the request was to register http://www.opengis.net/def/crs/OGC/0/LonLat84_5773 and not http://www.opengis.net/def/crs/OGC/0/CRS84.
> 
> Please register http://www.opengis.net/def/crs/OGC/0/LonLat84_5773

sorry, copy/paste during telecon:  http://www.opengis.net/def/crs/OGC/0/LonLat84_5773

**Comment by ghobona** [comment]
That's great! Thanks @pebau!
