### ISSUE TITLE
Well Known Scale Sets (WKSS)

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#18]
There are a number of Well Known Scale Sets identified in the OGC Two Dimensional Tile Matrix Set standard ([OGC 17-083r2](http://docs.opengeospatial.org/is/17-083r2/17-083r2.html)). These require registration in the Definitions Server.

**Comment by ghobona** [comment]
The examples are at http://schemas.opengis.net/tms/1.0/

**Comment by ghobona** [comment]
Initial WKSS register created at https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/wellKnownScaleSets/wkss.csv

**Comment by ghobona** [comment]
@joanma747 Please review.

**Comment by jyutzler** [comment]
Is it too much to ask for these to resolve to a metadata document? http://www.opengis.net/def/wkss/OGC/1.0/GlobalCRS84Scale doesn't really do anything for me.

**Comment by ghobona** [comment]
We craft them first on GitHub and then once they are approved by the OGC-NA we post them on the Definitions Server. They become resolvable once they are on the Definitions Server.

**Comment by dr-shorthair** [comment]
Could each URI go live as soon as requested, but with a status flag 'submitted' or similar. 
If an entry ends up having enough problems that it is not approved, then the status can indicate that. 
But there is significant value in having a URI go live in 'reserved' mode as soon as it is proposed, with only basic checks about syntax and clashes required. Too much governance (and paths with too many elements!) prevents well-founded testing.

**Comment by rob-metalinkage** [comment]
@jyutzler - thats the way the defs server is engineered - what we need to complete in a way we can scale is:
1) The metadata document itself, in what ever forms are desired (HTML, PDF, JSON, XML, RDF ?)
2) A predictable stable location for the metadata document
3) A data model for the metadata document
4) A profile description for the metadata document if its using a general model with specific rules
5) ideally a testable constraints specification for the metadata profile (schematron for XML, SHACL for RDF etc)

If its a one-off ad-hoc approach, then please just add a relationship to the register data (e.g. rdfs:seeAlso <URL> - or one of many other options for more specific typed links - rdfs:isDefinedBy etc. 

I am setting this sort of regime up for schemas - alpha testing at

https://defs-dev.opengis.net/def/schema/hy_features/hyf
and
https://defs-dev.opengis.net/def/schema/hy_features/hyf/HY_Catchment?_profile=alt&_mediatype=text/html

this uses a github repo called NamingAuthority

with the file location at:

/defintions/schema/<SWG shortname>/<schema code>/* 

note that we need to have a consistent set of resources for a type of definition to automate link handling this way.

**Comment by rob-metalinkage** [comment]
@dr-shorthair that is the plan - and indeed the way of things but it takes a little effort still.  We are working on an update to the front end that will allow us to make the status more visible rather than buried in the object attributes.  

I dont really have time allocated to the task, but it should be possible to have an automated reservation system - my suggestion is that at the upcoming TC the NA could bring such a policy at least to a testing and review mode and provide me with a direction on expected behaviour - or task me to propose one.

**Comment by rob-metalinkage** [comment]
@ghobona there is a brute force way of adding a status to an uploaded resource and it should entail the same status to all concepts in the scheme automatically.

open the scheme after load and before publishing and add additional metadata
policy:status <http://www.opengis.net/def/status/provisional>

(you could also add this into the source TTL file before upload)

**Comment by ghobona** [comment]
All, please move the discussion about the process of publishing provisional URIs to the the Issue https://github.com/opengeospatial/NamingAuthority/issues/50

This thread (https://github.com/opengeospatial/NamingAuthority/issues/18) should focus on WKSS.

**Comment by ghobona** [comment]
WKSS added with  Commit https://github.com/opengeospatial/NamingAuthority/commit/40a7d5c6cb0d2677f20d7df4aa14b337036e65a5
