### ISSUE TITLE
Pages from WPS schemas.opengis.net missing `Content-Type` header in responses

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/NamingAuthority#183]
Similar to #70 

All https://schemas.opengis.net/wps/ ... endpoints have stopped returning `Content-Type` header. 
I have not checked for other elements than WPS schema, but there could be other endpoints with similar issues.

The repo I work on has a test that checks the `Content-Type` returned by such endpoints 
(for example: http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd)

This commit was still passing (2022-06-13):
https://github.com/crim-ca/weaver/commit/8a61134679deb1212bac198c370297a92f8a15cf 

but recent ones fail (2022-07-05):
https://github.com/crim-ca/weaver/commit/9ec61c7448812461af248669eec8e920e55f807e
```
 =================================== FAILURES ===================================
________________ GenericApiRoutesTestCase.test_frontpage_format ________________
Traceback (most recent call last):
  File "/home/runner/work/weaver/weaver/tests/wps_restapi/test_api.py", line 56, in test_frontpage_format
    assert ctype in rtype, f"Reference link content does not match [{ctype}]!=[{rtype}] for {test}"
AssertionError: Reference link content does not match []!=[{'text/xml', 'application/xml'}] for (wps-schema-1) [http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd]
assert '' in {'application/xml', 'text/xml'}
```
https://github.com/crim-ca/weaver/runs/7204441836?check_suite_focus=true

Hopefully, this limits the time frame where the problem change can be identified.

**Comment by kstegemoller** [comment]
.xsd files is now served as

```
Content-Type: application/xml
```

**Comment by ghobona** [comment]
Thanks, @kstegemoller !

@fmigneault is the problem solved?

**Comment by fmigneault** [comment]
@ghobona Yes! Looks all good on my end also. Thanks
