### ISSUE TITLE
Only one seeAlso statement is displayed even when multiple seeAlso statements have been declared

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#192]
This was detected on the [tms.ttl#L175](https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/tms.ttl#L175) file. The same issue appears in other files.

**Comment by ghobona** [comment]
![Screenshot 2022-08-02 at 20 11 19](https://user-images.githubusercontent.com/18121038/182454735-9dffb9b6-a0cb-486f-bf3e-d36f341daad1.png)

**Comment by avillar** [comment]
@rob-metalinkage, I have disabled special treatment for annotation properties, just like we talked. They are now treated like any other additional property.

All seeAlso's now appear both in defs and defs-dev: https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/tilematrixset/OGC/1.0/CDB1GlobalGrid

Please confirm this is the desired result.

**Comment by ghobona** [comment]
That is indeed the result I was hoping for. Thanks.
