### ISSUE TITLE
Entail dcat:landingPage for all HTML references to http://docs.opengeospatial.org

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/NamingAuthority#200]
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX spec: <http://www.opengis.net/def/ont/modspec/>
PREFIX defs: <http://www.opengis.net/def/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (COUNT (?s) as ?num )
        WHERE {

                ?s skos:inScheme defs:docs .
                ?s rdfs:seeAlso ?a 
    FILTER ( STRSTARTS ( STR(?a) , "http://docs.opengeospatial.org" ) ) 
                }

**Comment by avillar** [comment]
I have the rule ready and tested. Should it go in `docs_entailments.shapes.ttl`, `skos_vocprez.shapes.ttl` or somewhere else?

**Comment by rob-metalinkage** [comment]
Docs.. its specific to this content.  We can refactor into a shared profile if we neef it again.
