### ISSUE TITLE
Incorrect use of `Universal` over `Uniform`

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/NamingAuthority#209]
In A.2.  URNs for Coordinate Reference Systems of _https://docs.opengeospatial.org/pol/09-048r6.html#toc23_

We have

> a) Universal Resource Locator (URL), with standard form. The URL format should be used whenever the referenced definition is known to be electronically available using this standard URL.

> b) Universal Resource Name (URN), with a specified form. The URN format shall be used whenever the referenced definition is not, or might not be, available using a URL. This URN shall reference data that is specified by some ‘authority’ and is ‘well-known’ to both client and server software, including multiple clients and multiple servers.

That's incorrect, the **U** in URL and URN stands for **Uniform** not **Universal**

**Comment by ghobona** [comment]
@nmtoken Agreed, that is indeed a typo. We will update the document at the next revision.
