### ISSUE TITLE
Media Types

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/NamingAuthority#21]
[OAB Issue 1404](https://portal.opengeospatial.org/?m=projects&a=view&project_id=228&tab=5&act=details&issue_id=1404)

Status: Open
Assigned To: Heazel, Charles
OAB Telecon 20200128

proposing that the OAB recommend that a new OGC policy and prodcess related to the definition, approval, and maintenance of OGC media types become a new responsibility of the OGC Naming Authority.

Related to 1436 - link types

ACTION: send background to OGC-NA for their discussion (including IANA) - Chuck to contact Gobe.  Include Issue 1436

**Comment by ghobona** [comment]
https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/mediaTypes/mediatyperegister.ttl

**Comment by cportele** [comment]
The official media type string registered by IANA is not really a skos:altLabel. It is the most important label. Perhaps switch with prefLabel? In the link relation types, the IANA string is also the prefLabel.

**Comment by pebau** [comment]
+1 for an OGC-central maintenance.
However, we should follow common Internet practice and rely on the standard naming, such as "image/tiff". Not only is this the format used in WCS, it is also a constant source of discomfort with users having to deal with the "unwieldy" OGC URLs. Maybe we can have both alternatives as synonyms.

**Comment by heidivanparys** [comment]
Could `skos:notation` maybe be used instead, for the official media type string?

From https://www.w3.org/TR/skos-reference/#labels :

> A lexical label is a string of UNICODE characters [...] in a given natural language, such as English or Japanese [...] The preferred and alternative labels are useful when generating or creating human-readable representations of a knowledge organization system. These labels provide the strongest clues as to the meaning of a SKOS concept.  [...]

From https://www.w3.org/TR/skos-reference/#notations :

> 
> A notation is a string of characters such as "T58.5" or "303.4833" used to uniquely identify a concept within the scope of a given concept scheme.
> 
> A notation is different from a lexical label in that a notation is not normally recognizable as a word or sequence of words in any natural language.


How about the IANA registry? Is that available somewhere as RDF? If yes, what is used there?

**Comment by dr-shorthair** [comment]
Yes to using `skos:notation` for the standard tokens

**Comment by rob-metalinkage** [comment]
The thing about skos:notation is that there may be multiple values - and they are supposed to be scoped by "datatype" - so we need a canonical URI for "This is an IANA media-type token"

maybe using https://www.iana.org/assignments/media-types ?

<http://www.opengis.net/def/media-type/ogc/1.0/geopackage>  skos:notation "application/geopackage+sqlite3"^^<https://www.iana.org/assignments/media-types>

Note this would allow us to have the short names for formats in OGC specs also registered as notations:

<http://www.opengis.net/def/media-type/ogc/1.0/gml> skos:notation "gml"^^<http://www.opengis.net/def/serviceType/ogc/wfs/1.0>

not that there might be nuances for different service types - so we could use explicit versions - but may also use a "Common" base specification.  I could probably entail all sub-types automatically in the definitions server - there wont be too many,

**Comment by pebau** [comment]
SKOS is not optimal from two perspectives:
- media types like "image/png" are well defined and used all over the place. Defining an island now is not helpful.
- from broad experiences with CRS URLs in coverages - where we have duly followed OGC-NA guidance earlier - it is well known (and often complained about) how unwieldy URLs are. Effectively, CIS/WCS is gently moving away from URLs by allowing strings like "EPSG:4726" as synonyms to the URLs, as is common in GIS world.

Hence, from a practitioner's perspective and as a compromise combining the best of all worlds let me suggest the same: allowing "image/png" plus have a synonym for http://www.opengis.net/def/media-type/image/png .
 
PS: And let us agree on not using the version number which is ill-defined and (mis)used in different ways in def/ .

**Comment by rob-metalinkage** [comment]
@pebau - I may be wrong, but the discussion about SKOS is not about embedding URIs where media-type tokens currently live - its about having a canonical mechanism to have a discoverable web object that tells you what this notation is.

Think of SKOS as purely the format of the "catalog record" in our register of tokens....

**Comment by pebau** [comment]
@rob-metalinkage, my apologies if I got this wrong. My impression was that a general identification mechanism was to be established for most, if not all services to use. Which would be a good thing, I like the idea that such identifiers can float around, and all use it the same, interchangeable way; for such a case I just wanted to keep the well-known synonyms. But then again, please ignore if not applicable in the first place.

**Comment by ghobona** [comment]
All,

Thanks for the suggestions and discussion. I'll update the CSV to reflect the approach proposed by @heidivanparys and @rob-metalinkage , specifically:

```
<http://www.opengis.net/def/media-type/ogc/1.0/geopackage> skos:notation "application/geopackage+sqlite3"^^<https://www.iana.org/assignments/media-types>
```

**Comment by ghobona** [comment]
I have just updated [mediatypes.csv](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/mediaTypes/mediatypes.csv) with commit https://github.com/opengeospatial/NamingAuthority/commit/d177571abeff30f1b1fd4fc412b9307a85ce8949

**Comment by ghobona** [comment]
[Turtle](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/mediaTypes/mediatypes.ttl ) files generated. They will be published on 30 May 2020 if there are no objections from [OGC-NA](https://lists.opengeospatial.org/mailman/private/ogc-na/2020-May/001019.html).

**Comment by ghobona** [comment]
The OGC Media Types register has been published at http://www.opengis.net/def/media-type/

**Comment by ghobona** [comment]
The OGC Media Types register moved to https://www.opengis.net/def/media-type/

Created a [skos:exactMatch](https://www.w3.org/2009/08/skos-reference/skos.html#exactMatch) from http://www.opengis.net/def/media-type/ to https://www.opengis.net/def/media-type/

**Comment by rob-metalinkage** [comment]
when we update the HTML viewer for the Defs Server one of my ambitions is to better handle the various issues around this.  Open to feedback from the field here.

A smartish client could automatically follow sameAs and/or exactMatch - but particularly some equivalent of rel='canonical' and bring in the preferred object details, with some sort of message about canonical status and bookmark/citation expectations. This would also handle the general issue for bookmarking objects by URI - not the redirected resource - as browser seem too dumb to handle the nuances of 3xx redirects. (Again, any insights welcome!)
