### ISSUE TITLE
Add .../crs/IAU/2015 to the list at .../crs/IAU

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#214]
@pebau Please add http://www.opengis.net/def/crs/IAU/2015 to the list at http://www.opengis.net/def/crs/IAU

So the new response will look as shown below:

```xml
<identifiers xmlns="http://www.opengis.net/crs-nts/1.0" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" at="http://www.opengis.net/def/crs/IAU/">
<identifier>http://www.opengis.net/def/crs/IAU/0</identifier>
<identifier>http://www.opengis.net/def/crs/IAU/2015</identifier>
</identifiers>
```

**Comment by ghobona** [comment]
Please note that the link (`/2015`) goes to the Planetary CRS register which is described in Issue https://github.com/opengeospatial/NamingAuthority/issues/212 .

**Comment by pebau** [comment]
@ghobona roger, will do, Gobe - please allow us until next week, the resp. staff is on vacation this week.

**Comment by pebau** [comment]
hm...looking at #212 I wonder what the envisaged structure is. IAU CRSs are served by OGC since years already, see https://www.opengis.net/def/crs/IAU/0 (initiated by Planetary scientist Angelo Pio Rossi) - I understand that a branch 2015/ is to be added? Which should redirect to another server?

**Comment by ghobona** [comment]
@pebau Yes, you are right. It is probably best to implement it through a corresponding redirect in the OGC server. Thanks for the idea.

I'll work with @kstegemoller to set up the relevant redirect.

No action needed, for now. So I am closing the issue.
