### ISSUE TITLE
TMS UTM60WGS84Quad is missing from definition server

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#215]
This was buried in https://github.com/opengeospatial/NamingAuthority/issues/199#issuecomment-1263337021 that was just closed.

See http://www.opengis.net/def/tilematrixset/OGC/1.0/UTM60WGS84Quad

http://www.opengis.net/def/tilematrixset/OGC/1.0/UTM59WGS84Quad works fine.

The source file is at:

https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/registry/json/UTM60WGS84Quad.json

XML: https://raw.githubusercontent.com/opengeospatial/2D-Tile-Matrix-Set/master/registry/xml/UTM60WGS84Quad.xml

**Comment by ghobona** [comment]
Just published.

<img width="970" alt="Screenshot 2023-06-04 at 12 34 18" src="https://github.com/opengeospatial/NamingAuthority/assets/18121038/bb0202fb-d490-43b1-a30b-ef44946a717d">

**Comment by jerstlouis** [comment]
Awesome, thanks @ghobona
