### ISSUE TITLE
Add the rel types to NA registry after OGC API maps go to OAB

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/NamingAuthority#216]
* **http://www.opengis.net/def/rel/ogc/1.0/map**: Refers to a resource that is map representation of another geospatial resource (e.g. a collection)
* **http://www.opengis.net/def/rel/ogc/1.0/legend**: Refers to a legend for the map

**Comment by ghobona** [comment]
These have been added using `https` as the protocol of the identifier in accordance with OGC API - Maps - Part 1: Core.

An `http` alias was not created.
