### ISSUE TITLE
Cannot find NIL values definitions

### ISSUE THREAD

**Issue by alexrobin** [opengeospatial/NamingAuthority#221]
There used to be definitions and stable URIs for NIL reasons registered on the definition server, such as:

- http://www.opengis.net/def/nil/OGC/0/BelowDetectionRange
- http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange
- http://www.opengis.net/def/nil/OGC/0/Missing
- http://www.opengis.net/def/nil/OGC/0/Unknown
- etc.

I cannot resolve these URIs nor find the corresponding definitions anywhere in the definition server tree. Were they removed on purpose or by mistake?

Thanks.

**Comment by rob-metalinkage** [comment]
Will check.

**Comment by rob-metalinkage** [comment]
The content is there - but the new UI requires some metadata for the concept scheme that is missing.  The new validation pipeline actually picks this up but we haven't had time to remediate all the legacy content. 

Severity: sh:Violation
	Source Shape: <https://w3id.org/profile/vocpub/shapes/Requirement-2.3.3>
	Focus Node: <http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange>
	Value Node: <http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange>
	Message: Requirement 2.3.3 Each skos:Concept in a vocabulary _MUST_ indicate that it appears within that vocabulary's hierarchy of terms by use of either or both `skos:inScheme` and `skos:topConceptOf` properties
Constraint Violation in OrConstraintComponent (http://www.w3.org/ns/shacl#OrConstraintComponent):

The bigger issue I'll deal with is that the content scheme is bundled into a larger original file with other stuff so its not entailing things properly - I'll factor the scheme out into a separate file as per normal practice and see if it resolves it.

**Comment by rob-metalinkage** [comment]
Should be working now - please report any issues

note you can access the full vocabulary now via  http://www.opengis.net/def/nil?_profile=alt

e.g.
http://www.opengis.net/def/nil?_profile=conceptscheme&_mediatype=application/ld%2Bjson


(this is why we refactor into separate concept schemes - havent dealt with all the legacy yet :-(  - will riase an issue for this

**Comment by alexrobin** [comment]
I confirm it's working now.
Thanks Rob.

**Comment by rob-metalinkage** [comment]
this is what was there previously

 owl:sameAs <http://www.opengis.net/def/nil/ogc/0/> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/BelowDetectionRange> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/inapplicable> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/missing> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/template> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/unknown> ;
  skos:member <http://www.opengis.net/def/nil/OGC/0/withheld> ;

and

<http://www.opengis.net/def/nil/OGC/0/missing>
 rdfs:label "missing"@en ;
  owl:sameAs <http://www.opengis.net/def/nil/ogc/0/missing> ;
  skos:altLabel "Missing"@en ;

so i dont think these could have been there. There has never been any case conversion happening AFAIK

**Comment by alexrobin** [comment]
Yes, you're right, my bad.
We had them as lowercase in our software all along actually.

What through me off is that http://www.opengis.net/def/nil/OGC/0/AboveDetectionRange also exists as http://www.opengis.net/def/nil/ogc/0/above-detection-range for example.
