### ISSUE TITLE
Internal Server Errors for definition server

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/NamingAuthority#227]
These result in 500 Internal Server Errors:

https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/derivedCRSType/OGC/1.1/vertical
https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/verticalDatumType/OGC/1.0/barometric

**Comment by avillar** [comment]
`http://www.opengis.net/def/derivedCRSType/OGC/1.1/vertical` and `http://www.opengis.net/def/verticalDatumType/OGC/1.0/barometric` are both missing `skos:inScheme`, so VocPrez fails.

[Validation is failing](https://github.com/opengeospatial/NamingAuthority/blob/acbed38b77b279ccffd85165d876afc26f3041ae/definitions/conceptschemes/ogc.txt#L940), too, for the same reason.

A quick SPARQL query shows 127 concepts with this same problem.

**Comment by rob-metalinkage** [comment]
We will check the new version doesn't fail this way.  And fix the data.  Can we identify the custodian of thus content?

**Comment by jerstlouis** [comment]
@rob-metalinkage Roger Lott actually mentioned that the "barometric" datum type has been abandoned in favor of the use of parameteric CRSs:

> A vertical subtype barometric was included in early drafts of Topic 2 (before about 2005, maybe even earlier) but was removed as a vertical subtype and generalised into parametric before the final adoption of Topic 2 and ISO 19111 in 2007. Vertical CRS now is explicitly a geometric coordinate system in the earth's gravity vector.

I am not sure however if that is in line with the EDR approach, which introduced a `"vrs"` type and most likekly uses this for pressure levels. Related to #228 .

@chris-little @m-burgoyne

**Comment by rob-metalinkage** [comment]
Note that the Naming Authority manages the registry ( function ) so we will fix the errors.  The Register "control body" needs to decide on content issues.  First we need to identify the control body and initiate the decision making process.

**Comment by jerstlouis** [comment]
@rob-metalinkage Yes this issue was specifically about the 500 "function" error.
The CRS SWG I believe would be the relevant control body in this case.

**Comment by KathiSchleidt** [comment]
A short note that you also have some issues on the dev version. I was discussing the GloSIS w3ids Raul Palma recently included in the dev-def server at the edge of EGU this week, we noticed that:

- https://defs-dev.opengis.net/vocprez-hosted/object?uri=http://w3id.org/glosis/model/codelists/physioChemicalPropertyCode fails
- https://defs-dev.opengis.net/vocprez-hosted/object?uri=http%3A//w3id.org/glosis/model/codelists/physioChemicalPropertyCode works

Seems the : must be encoded, to  my feeling should be either the entirety of the passed URI, or none of it
