### ISSUE TITLE
No navigation to OGC Glossary of Terms from Definitions Server Landing Page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#23]
There does not appear to be a way to navigate to the OGC Glossary of Terms from the Definitions Server Landing Page.

Issue discovered by @estubkjaer

**Comment by rob-metalinkage** [comment]
The file ogc_glossary.ttl contains a statement

<http://www.opengis.net/def/>
      skos:member <http://www.opengis.net/def/glossary/> .

but this is not being captured in the load to a ConceptScheme - hence isnt propagating to the final repository.

I'll create a ticket to support collection membership across concept schemes.

the question is where should it appear - under 
/def/
or /def/ogc/

and should it be a "special case" - a metadata property such as rdfs:seeAlso from /def/  ?

**Comment by ghobona** [comment]
I suggest making the glossary a member of http://www.opengis.net/def/ogc/

**Comment by ghobona** [comment]
Based on the discussion in Ottawa to redo the Glossary, I have set it up as a [register](http://www.opengis.net/def/register/).

The commit is: https://github.com/opengeospatial/NamingAuthority/commit/cbef999b1d1ea33e05b3017befde49d28d776fe4
