### ISSUE TITLE
new terms according to Location Innovation Academy

### ISSUE THREAD

**Issue by nilshempelmann** [opengeospatial/NamingAuthority#234]
A Glossary had been established in the frame of the GEOE3 project and included in the e-learning platform (currently running under the URL: https://academy.ogc.org ). 

this Academy includes a Glossary, which will be linked to the OGC definitions. 

Here is a list of words to be included in the OGC Glossary
https://docs.google.com/document/d/1MiFLwlezGxcGafJiSq8TbHVQ_N5Ve2SnR_vHWpB4gZE/edit

**Comment by ReesePlews** [comment]
hello @nilshempelmann is it possible to receive a copy of these terms, i could not access the google doc? 
reese plews
convenor,  iso/tc211 terminology maintenance group

**Comment by nilshempelmann** [comment]
@ReesePlews 
See the document attached here. 
[Terms for the glossary.docx](https://github.com/opengeospatial/NamingAuthority/files/12378687/Terms.for.the.glossary.docx)

**Comment by ghobona** [comment]
The additional terms have now been [published](https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/glossary).
