### ISSUE TITLE
Register GeoSPARQL definitions

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#238]
The URIs in the attached spreadsheet were submitted by the GeoSPARQL SWG on 2023-05-31.

[Names Request.xlsx](https://github.com/opengeospatial/NamingAuthority/files/12438719/Names.Request.xlsx)

Note that this GitHub Issue should only discuss the definitions (i.e. URIs with a `/def` segment).

**Comment by ghobona** [comment]
**Issue 238A**

These returned a 404 error

https://opengeospatial.github.io/ogc-geosparql/geosparql10/servicedescription_allfunctions.html

https://opengeospatial.github.io/ogc-geosparql/geosparql11/servicedescription_allfunctions.html

After checking GitHub Pages, _allfunctions.html was changed to _all_functions.html

Noted that the v1.0 turtle file still has _allfunctions.ttl. Let the name of the turtle file unchanged. However, I recommend changing it to match the name of the HTML file (i.e. _all_functions).

Noted that the name of the v1.1 file correctly matches that of the HTML file. (i.e. _all_functions)

FIXED.

—————
**Issue 238B**

This one also returned a 404 error.

https://opengeospatial.github.io/ogc-geosparql/geosparql11/funcsrules.html

When checking GitHub Pages, we noticed that there is no HTML encoding available.


————
**Issue 238C**

This one also returned a 404 error.

https://opengeospatial.github.io/ogc-geosparql/geosparql11/geosparqlreq.ttl 

After checking GitHub Pages, it was changed to  https://opengeospatial.github.io/ogc-geosparql/geosparql11/reqs.ttl

———

**Issue 238D**

Multiple URIs did not follow the patten specified in [Clause 5.2](https://docs.ogc.org/pol/09-048r6.html#toc13) of the OGC-NA definitions policy, therefore a revision to the URIs has been proposed.

Some resources in the initial proposal were duplicated but with different URIs, therefore those duplications have been omitted in favour of the URIs that have version numbers. The omitted URIs are:

- http://www.opengis.net/def/geosparql
- http://www.opengis.net/def/geosparql/servicedescallfunctions
- http://www.opengis.net/def/geosparql/servicedescconformanceclasses

———

**Comment by ghobona** [comment]
After review, the URIs are proposed to be revised as shown in [this table](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/geosparql/NamesRequest.csv).

**Comment by nicholascar** [comment]
v1.0 turtle file still has been renamed to _all_functions.ttl

**Comment by nicholascar** [comment]
Issue 238B is now fixed - offline HTML file generation

**Comment by nicholascar** [comment]
> Issue 238D

Clause 52 says that the version is an optional field. so we would like the un-versioned forms of IRIs to point to the latest version. This means:

* http://www.opengis.net/.../1.0 -> A 1.0 version of something
* http://www.opengis.net/.../1.1 -> A 1.1 version of something
* http://www.opengis.net/... -> A the latest version which is currently 1.1

Also, in your response table above, you have indicated a "GeoSPARQL 1.0 Ontology", a "GeoSPARQL 1.1 Ontology" and a "GeoSPARQL Base Ontology", so following my logic above, the "GeoSPARQL Base Ontology" is currently the "GeoSPARQL 1.1 Ontology", so you can add the 1.1 resources to the "Location of resource in HTML" and "Location of resource in TTL".

**Comment by ghobona** [comment]
The mappings have been submitted to the Infrastructure Office for activation.

**Comment by ghobona** [comment]
@nicholascar Please note that there are some GeoSPARQL 1.0 definitions that were published 5 years ago [here](https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/functions_geosparql.ttl). Does the SWG wish to label them deprecated or to retain them in parallel with the new ones?

**Comment by ghobona** [comment]
@nicholascar In addition to the question above, the TTL and JSON-LD files have not been updated with the revised URIs. Could you please update the TTL and JSON-LD files?

**Comment by ghobona** [comment]
@nicholascar I have gone ahead and uploaded the triples from the TTLs that are in the gh-pages branch into OGC RAINBOW.

The ConceptSchemes can be seen [here](https://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/).

There are some URIs that had not been declared as skos concepts, conceptschemes, nor collections. Most have been fixed, however there may be others. So they will be fixed when we discover them.

As the supplied TTL files have been now been uploaded, I am closing this GitHub Issue.
