### ISSUE TITLE
Register GeoSPARQL documents

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#241]
The URIs in the attached spreadsheet were submitted by the GeoSPARQL SWG on 2023-05-31.

[Names Request.xlsx](https://github.com/opengeospatial/NamingAuthority/files/12438719/Names.Request.xlsx)

Note that this GitHub Issue should only discuss the documents (i.e. URIs with a `/doc` segment).

**Comment by ghobona** [comment]
The document URIs are Persistent URLs (PURLs), so OGC Staff generally enable them once the documents have been approved by the Technical Committee and published.

**Comment by nicholascar** [comment]
Where do I get `/ont` IRIs from then? `/ont` was used in 2012 for GeoSPARQL 1.0 (viz.: `http://www.opengis.net/ont/geosparql` that resolves to RDF/XML). We want to update this to resolve to GeoSPARQL 1.1's RDF/Turtle data at https://raw.githubusercontent.com/opengeospatial/ogc-geosparql/master/1.1/geo.ttl

**Comment by ghobona** [comment]
@nicholascar 

GeoSPARQL 1.0: Currently that is implemented as a redirect from `http://www.opengis.net/ont/geosparql` to `http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf`.

EO-GeoJSON: Currently the redirect is not enabled. The target would be `https://schemas.opengis.net/eo-geojson/1.0/eo-geojson-vocabulary.owl`. There are also JSON-LD and Turtle files in the same folder.

**Comment by nicholascar** [comment]
OK, I understand, this issue is about `/doc` and #240 is about `/ont` (and #238 is about `/def`)

**Comment by nicholascar** [comment]
@ghobona can this issue please be completed and can we have the doc identifier, http://www.opengis.net/doc/IS/geosparql/1.1, pointing to the HTML at https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html?

**Comment by nicholascar** [comment]
Hi @ghobona can I just check: is is this Issue that, when closed, will have make the GeoSPARQL doc IRI of <http://www.opengis.net/doc/IS/geosparql/1.1> work? This IRI is the most critical one for us regarding visibility of the GeoSPARQL 1.1 specification document at <https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.html>

**Comment by ghobona** [comment]
@nicholascar The IRI will be enabled once the Standard is published. It will not take long to enable the IRI but we have to make sure that the Standard document is ready, because errors post-publication would require a Corrigendum.

**Comment by nicholascar** [comment]
Hi @ghobona what do you mean by "once the Standard is published"? We - the DWG - are waiting for these IRIs to be allocated so we can put them in the document and put out media releases for the standard but you seem to be waiting for some other step to issue the IRIs. What is that other step? The standard has been approved as far as we can tell so what do you need from who to issue this IRI.

**Comment by ghobona** [comment]
@nicholascar When the Standard is published it is released through the OGC website, at an address that begins with `https://portal.ogc.org/files/?artifact_id=A_NUMBER`.

A record is then created on the page https://www.ogc.org/standard/geosparql/ , with a link for downloading/accessing the Standard document.

The IRI `http://www.opengis.net/doc/IS/geosparql/1.1` will then be configured to redirect/proxy through to `https://portal.ogc.org/files/?artifact_id=A_NUMBER`

I sent the @jabhay my review of the Standard document last week. Once the requested edits have been made, the SWG should let @ogcscotts know so that we can proceed with the publication of the Standard.

Please note that @situx has fixed [some of the issues](https://github.com/opengeospatial/ogc-geosparql/pulls). So you will need to coordinate with @situx and @jabhay on making the requested edits.

**Comment by nicholascar** [comment]
@ghobona, ok we - @situx, me and the GeoSPARQL DWG - are addressing the three issues you raised on the GeoSPARQL document now and, when don, we will let @ogcscotts know. Thanks for clearing up this step

**Comment by ghobona** [comment]
This URI has now been enabled http://www.opengis.net/doc/IS/geosparql/1.1

The URIs of specification elements have also been enabled https://github.com/opengeospatial/NamingAuthority/blob/master/specification-elements/mappings/22-047r1.csv
