### ISSUE TITLE
Register nearest-neighbor interpolation method

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#245]
The URI is from the approved WCS Interpolation Extension v1.0 (OGC 12-049).

http://www.opengis.net/def/interpolation/OGC/1/nearest-neighbor

**Comment by pebau** [comment]
Let me suggest to establish an interpolation/ branch listing more than just the one above. I know of 2 sources:
- ISO 19123-1 and its predecessor OGC AT6 define nearest-neighbor, linear, quadratic, cubic, barycentric on coverage data;
- GML 3.2.1 has several interpolation types in geometryPrimitives.xsd for curves and surfaces.

Q: any further sources of interpolation methods known?

Next, there is no schema - it always is only an identifier in a codelist. So someone would need to craft a (rudimentary) XML schema for it. Descriptions could be taken from ISO 19123-1 and 19107.

Q: who can do such a schema?

**Comment by ghobona** [comment]
Published [here](url).
