### ISSUE TITLE
Links in README

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/NamingAuthority#26]
There is a stale link in the README. https://github.com/opengeospatial/OGC-NA

Also, it would he useful to link this repository to where the policies and procedures live. The Naming Authority and how to engage is a bit impenetrable. 

Maybe: https://www.ogc.org/standards/na ?

**Comment by ghobona** [comment]
Done.

Added link to approved policies and procedures. https://github.com/opengeospatial/NamingAuthority/commit/18e18efed8baa4b67a3916185e32e6aa88319bd2

Removed the link to the Private OGC-NA repo. https://github.com/opengeospatial/NamingAuthority/commit/9984cf11620132c45c7a49119d47e87b4f04ed96
