### ISSUE TITLE
Look into why http://www.opengis.net/def/ogc-na is not accessible from RAINBOW

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#261]
The ontology is [here](https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/ogc-na.ttl#L139) but currently it returns a status 400 error code.

http://www.opengis.net/def/ogc-na

![Screenshot 2023-10-17 at 20 30 19](https://github.com/opengeospatial/NamingAuthority/assets/18121038/664dafab-3f41-45ea-8f07-8944a9ba48e5)

**Comment by avillar** [comment]
Is that file correctly loaded in defs? Running the following SPARQL query:

```sparql
select * where { {<http://www.opengis.net/def/ogc-na> ?hasProperty ?o } UNION {?o ?isPropertyOf <http://www.opengis.net/def/ogc-na>} }
```
Returns no triples where <http://www.opengis.net/def/ogc-na> is the subject (the isDefinedBy from <http://www.opengis.net/def/ogc-na/> is there, though)...

**Comment by avillar** [comment]
On defs-dev it seems to be ok:

![imagen](https://github.com/opengeospatial/NamingAuthority/assets/3385355/8d183f3b-e8ab-4cd2-83b6-2a98d3fe2050)

**Comment by rob-metalinkage** [comment]
the ogc-na.ttl source file was a legacy that has been refactored to extract a lot of the ConceptSchemes it defined - but its probably not published via the CMS - but rather by the ansible setup - i suspect it needs to be pushed manually to defs in the interim.
