### ISSUE TITLE
Units registered in the OGC Rainbow

### ISSUE THREAD

**Issue by cportele** [opengeospatial/NamingAuthority#263]
The Features API SWG requires a language to unambiguously encode units of measurement. We also looked at the [units registered in the OGC Rainbow](https://www.opengis.net/def/uom) and were quite confused by the fact that

* there are very few entries;
* of many units there are multiple entries (e.g., "metre" is defined six times).

After a closer look I understand that the multiple instances are for meter in different authorities (and for URIs that do not conform to the policy, but are probably maintained for legacy reasons).

However, it was still unclear to us what the status of the OGC definitions for units is. Especially since only very few units are registered. Is the conclusion correct that the recommendation is to use more widely used approaches (UCUM, QUDT Units) instead of an OGC-specific one? That is, the OGC units are basically deprecated and only maintained because they were registered at some point in the past?

**Comment by dr-shorthair** [comment]
FWIW QUDT is actively maintained. 
There is a public issue tracker, many contributors 
https://github.com/qudt/qudt-public-repo/graphs/contributors
and PRs are processed frequently - https://github.com/qudt/qudt-public-repo/pulls?q=is%3Apr+

**Comment by ghobona** [comment]
The outcome of a similar discussion regarding GeoSPARQL is [here](https://github.com/opengeospatial/NamingAuthority/issues/80#issuecomment-871540569).

In that situation, the decision of which UOM URI to use was delegated to the GeoSPARQL SWG.  

The GeoSPARQL SWG decided to use QUDT. So there is a precedent for using QUDT.

**Comment by cportele** [comment]
Thanks for the reminder about the old discussion, @ghobona. My conclusion from that discussion is that we (Features API SWG) should use established approaches for expressing units, which likely means UCUM or QUDT Units. For now, we have settled on UCUM as the default, because it is a general grammar for expressing units and URIs for the units are not important.

I am closing this issue again, because the question about the units in the Definitions Server has been answered. Thank you.

**Comment by dr-shorthair** [comment]
Note that the guys at St Etienne have specified an RDF Datatype for a microformat using UCUM. This has some uptake. 
https://w3id.org/cdt/ucum

**Comment by cportele** [comment]
Interesting @dr-shorthair. This can be useful for cases where the unit cannot be constant and where filtering on the values is not important.
