### ISSUE TITLE
User Interface not displaying extensionAggregate nor extensionFunction

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#267]
According to [this](https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/servicedescription/servicedescription_all_functions.ttl#L23) extensionAggregate and extensionFunction should be displayed in http://www.opengis.net/def/geosparql/servicedescription, however none of the objects is listed.

**Comment by avillar** [comment]
Apparently VocPrez doesn't render any Concept Scheme properties that don't have labels.

Fixed by uploading the [SPARQL 1.1 Service Description](http://www.w3.org/TR/sparql11-service-description/) vocabulary to the triplestore.
