### ISSUE TITLE
Would it be possible for you to provide SKOS versions of CRS definitions?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#27]
This question came through the mailing list https://lists.opengeospatial.org/mailman/private/ogc-na/2020-February/000994.html

**Comment by ghobona** [comment]
Follow the discussion on the mailing list.

**Comment by nicholascar** [comment]
@situx, here is the request make to make SKOS versions of the CRS definitions available. I think I even provided a SKOS file to the Naming Authority. Your ontology (please link to it here) would create a potential additional profile for each CRS.

**Comment by situx** [comment]
https://github.com/situx/proj4rdf
This is the link. However, the ontology is likely not finished. It is a work in progress to extract information about CRS from proj4 to RDF. We should possibly consolidate this with the SKOS definitions if available

**Comment by rob-metalinkage** [comment]
Remove Definitions Server label - this is not about the def server implementation, but is about a new content activity.

**Comment by ghobona** [comment]
Question sent to CRS SWG and CRS DWG.

https://lists.ogc.org/mailman/private/coordtran.wg/2021-May/002553.html

**Comment by ghobona** [comment]
The Joint CRS SWG/DWG discussed this topic on June 15th, 2021 and responded that there is currently no Business Case for a SKOS representation of CRS.

The Joint CRS SWG/DWG also noted that although a SKOS representation of CRS isn't critical today, it may be in several years time as practical use of the Semantic Web becomes more widespread. Further, the type of queries and logic achievable through Semantic Web tools could help to identify shortcomings of some other encodings.

However, the Joint CRS SWG/DWG also noted a concern that there is a risk that the SKOS encoding could be developed and then five years down the road there would  be nobody around to maintain it. Therefore it is necessary to identify if there is a Business Case for it. 

A Business Case could be established by identifying a number of OGC Members that have a need for the specification, that are willing to develop and maintain the specification, as well as willing to implement software that complies to the specification. Work on the specification could then be proposed as a Work Item in the CRS SWG Charter.
