### ISSUE TITLE
Update document policy to use DOIs as external-ids

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#281]
The DocTeam meeting of 23 April 2024 recommended that the OGC policy on documents be updated to use DOIs as the external-id.

**Comment by dr-shorthair** [comment]
Very good.

**Comment by dr-shorthair** [comment]
Good to see this, but the BNF in the rendered document shows 
`URI = "https://doi.org/10.62973/"/> DOISuffix` 

I think `"/>` is probably incorrect.

**Comment by ghobona** [comment]
@dr-shorthair Thanks for spotting the issue. I have just updated the document.

I also replaced the TBA in the DOI examples. The examples are yet to be enabled but explain the approach that we are considering.
