### ISSUE TITLE
Ready for OGC-NA Review: OGC API - Connected Systems - Part 1: Feature Resources

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#282]
OGC-NA,

The document(s) titled "OGC API - Connected Systems - Part 1: Feature Resources" is/are now available for review by the OGC Naming Authority (OGC-NA) Subcommittee.

https://docs.ogc.org/DRAFTS/23-001r0.html

Please review the documents by 22:00 UTC on May 3, 2024 focusing on its conformance to OGC-NA policies.

OGC-NA policies can be found at https://www.ogc.org/standards/na

The most relevant policies are:

- OGC-NA Name type specification - definitions (09-048r6)
- OGC-NA Name type specification - specification elements (10-103r1)

Let us know before then if there are any comments or objections to unanimous consent to its approval by the OGC-NA.

Regards,

OGC Staff

**Comment by ghobona** [comment]
Noting that the [SensorML requirements class](https://docs.ogc.org/DRAFTS/23-001r0.html#_media_type_2f) specifies a media type of `application/sml+json`.

Since the media type is not yet registered with IANA, I think this should be in the vendor ([vnd.](https://en.wikipedia.org/wiki/Media_type#Vendor_tree)) tree instead.

**Comment by ghobona** [comment]
The document currently uses the following term. 

UAS: Unmanned Aerial System

ISO 5305 defines UAS as unmanned aircraft system, see https://www.iso.org/obp/ui/en/#iso:std:iso:5305:ed-1:v1:en

ISO 23665, ISO 21384, and ISO 4358 also use the term ‘unmanned aircraft system’.

The UxS DWG uses the term Uninhabited System.

https://www.ogc.org/about-ogc/committees/dwg/uninhabited-systems-domain-working-group/

**Comment by ghobona** [comment]
Some URIs appear to have placeholders (e.g. TBD) in them.

See Tables 6, 10, and 15. 

See also the Example underneath Table 21

**Comment by dr-shorthair** [comment]
Alex -

I noticed an inconsistency on the definition of one of the Sampling Feature Associations in Table 17

sampledFeature	sosa:isSampleOf	he ultimate feature of interest that is being sampled or controlled.
In OMS and SSN, the relation isSampleOf​ links a Sample to the proximate​ feature of interest, not the ultimate FoI. There may then be a chain of further samples before you reach the ultimate FoI. The additional properties hasOriginalSample​ and hasSampledFeature​ provide shortcuts. See diagrams in the SSN-Ext paper, which inspired OMS and the SSN update - https://www.w3.org/TR/vocab-ssn-ext/#ultimate-feature-of-interest

Perhaps we should add these diagrams and explanation into the SSN update, in the Common Modeling Questions section?

Cheers - Simon

***@***.***
+61 403 302 672

On Boonwurrung land

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by ghobona** [comment]
@alexrobin Please see the comments above.

**Comment by alexrobin** [comment]
@gobona I'm glad you created this issue since we wanted to seek advice from the OGC NA on these topics.

Regarding media types, is there a need/good reason to register them with IANA ultimately, or are we happy with something in `vnd.ogc` namespace for the entire life of the standard? I don't mind either way. Less work is good ;-)  Is the `vnd.ogc` namespace registered officially?

Regarding our custom URIs, is the recommendation to host these in the OGC definition server? If so,what's the process to do that these days?

**Comment by dr-shorthair** [comment]
Hi Kathi,

No, the definitions haven't diverged.
This just means that all the platforms that are under a System collection
are both sosa:Platform and sosa:System as per the discussion we had in the
SOSA/SSN WG.

See my comment here:
https://github.com/opengeospatial/ogcapi-connected-systems/issues/52

Thanks,


--

Alex Robin

Chief Technology Officer | GeoRobotix Inc. | +1 302 703 7072

**Comment by ghobona** [comment]
@alexrobin Ultimately,  the goal is to register `application/sml+json` with IANA. However, it may take a while, therefore a note similar to the [JSON-FG one](https://docs.ogc.org/DRAFTS/21-045r1.html#media-types) would is ideal.

So by all means, please keep `application/sml+json`. However, include a note that allows for the `vnd` type as well until the registration is completed.

**Comment by ghobona** [comment]
@alexrobin One of the nice things about metanorma is that it highlights dangling links between requirements classes and requirements. Several requirements classes appear reference requirements that no longer exist. See an example on the attached screenshot.

![Screenshot 2024-08-14 at 15 31 36](https://github.com/user-attachments/assets/21776894-05f2-41d5-8c1d-61250bd052a0)
