### ISSUE TITLE
Undisplayed CaLAThe triple

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#38]
The following triple is not being displayed. 

```
<http://www.opengis.net/def/ogc/> <http://www.w3.org/2004/02/skos/core#member>  <https://www.opengis.net/def/CaLAThe>.
```

I reimported CaLAThe this morning and expected the triple to show because it is [in the file](https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/CaLAThe.ttl#L8).

**Comment by rob-metalinkage** [comment]
OK - I'll need to check these statements actually get imported - I suspect that statements about membership of other concept schemes are not actually supported. Its a little bit of a governance issue - importing changing a concept scheme you don't own.  I think I would need to add an "inverse properties" section to the django data model and include this in the serialisation rules. need to think about it.

**Comment by rob-metalinkage** [comment]
Have added it manually for now but need to get a better solution

**Comment by ghobona** [comment]
Thanks!
