### ISSUE TITLE
CaLAThe - Rendering of transitives

### ISSUE THREAD

**Issue by estubkjaer** [opengeospatial/NamingAuthority#40]
The idea of rendering of transitives has to be reconsidered.  
Generally, it seems that all narrower transitive of e.g. Activity is rendered in alphabetical order, without indication of level. The rendered batch of concept labels are confusing the user, because 'Amalgamation' is narrower of 'Property formation', while the following  'Conveyance' is narrower of 'Exchange'. In other cases, e.g. Boundary, information is duplicated.
Options:
 1. All transitives are avoided
 2. Transitives are rendered with in-between concept labels

Preferred is 1, because the user may explore concept relations by clicking on the narrower or broader concept labels.

Examples:
Activity 
https://defs.opengis.net/elda-common/ogc-def/resource?uri=https://www.opengis.net/def/CaLAThe/4.0/Activity&_format=html

Boundary
https://defs.opengis.net/elda-common/ogc-def/resource?uri=https://www.opengis.net/def/CaLAThe/4.0/Boundary&_format=html

**Comment by rob-metalinkage** [comment]
I think its probably OK to disable inferencing of transitives.  Hope to upgrade the UI at some stage and will explore showing objects in heirarchies in a better way.

**Comment by rob-metalinkage** [comment]
PS - I need to update the inferencing rules, test, install and republish.  you dont need to do anything. assigning to me

**Comment by rob-metalinkage** [comment]
I have removed narrower transitives - I can generate a profile option to provided narrower transitives and/or depth traversal of heirarchies as an option.  Broader transitives are all valid statements about the concept - I am going to propose leaving this in by default - but we can address this in future.

**Comment by estubkjaer** [comment]
Narrower transitives: Depth traversal of heirarchies is my preferred option

Broader transitives: 
Example1: 'Land division' renders 
broader transitive 
    Land 
    Spatial feature ..

Comment: Land (which is the topConcept) is not emphasized, while 'Spatial feature' is, but the latter brings no new information.

Example 2: 'Cadastral parcel' renders
broader transitive
    Land division
    Property unit

Comment: Agree that "Broader transitives are all valid statements", but it seems that level depth is limited to two, implying that not all broader transitives are rendered. 
The rendering of topConcept only seems to me to provide the most relevant information regarding Broader transitives

**Comment by rob-metalinkage** [comment]
In example 1, this is a sad limitation of the rendering choices hard-coded - I dont think I can fix either data or templates to work around this easily. Will confer with OGC management about how to progress this. 

#2 - yes there is a problem here in the inferencing - will fix,

**Comment by rob-metalinkage** [comment]
Should have fixed the broaderTransitive issue - please check.

**Comment by estubkjaer** [comment]
Testing with 
https://defs.opengis.net/elda-common/ogc-def/resource?uri=https://www.opengis.net/def/CaLAThe/4.0/PostalAddress&_format=html

rendered a complete batch of broader transitives -> depth level issue solved.

The broader transitives are rendered in alphabetical order, rather then preferred: visualizing the concept hierarchy either as text: 
topConcept1 <- concept2 <- concept3 <- concept4 ..
topConcept2 <- concept5 <- concept6 <- concept7 ..

or as graphs, cf. 
http://labs.sparna.fr/skos-play/
or
https://github.com/jsongraph with https://github.com/jsongraph/jgf-dot

We can leave it here, or open a new issue?

**Comment by rob-metalinkage** [comment]
when I have better control over UI then rendering the hierarchy can be achieved in a better way,

**Comment by ghobona** [comment]
As discussed with @rob-metalinkage and @estubkjaer , following the UI upgrade, this issue can now been closed.
