### ISSUE TITLE
CaLAThe - Rendering of code list content (Initial capitalized or not)

### ISSUE THREAD

**Issue by estubkjaer** [opengeospatial/NamingAuthority#42]
Problem: Initials are not capitalized or not as rendered by the prefLabel

Examples:
building part type  /  BuildingPartType 
https://defs.opengis.net/elda-common/ogc-def/resource?uri=https://www.opengis.net/def/CaLATheCodeList/4.0/BuildingPartType&_format=html

survey monument type  / SurveyMonumentType 
https://defs.opengis.net/elda-common/ogc-def/resource?uri=https://www.opengis.net/def/CaLATheCodeList/4.0/SurveyMonumentType&_format=html

Background:
The code list names are all in the CaLATheCodeList scheme, but the code list values may refer to concepts of the CaLAThe concept scheme ('CaLAThe proper')

The prefLabel of code list names are rendered with capitals, e.g. SurveyMonumentType 
while code list values generally are rendered without, e.g. prefLabel 'other mark'
UNLESS the code list value refers to a concept of the CaLAThe concept scheme, where all prefLabels start with capitals, e.g.  Boundary mark and Trigonometric mark

Motivation is found in #41 

The above rules may be violated; for example Parcel establishment exists in CaLAThe proper, as narrower of Property formation, with prefLabel 'Parcel establishment', and also in the code list StatementType with prefLabel 'parcelEstablishment'
The rule violation is addressed in the submitted as follows:
> Next code list is strongly related to CaLAThe's Activity part, but as domain relations are not yet elaborated, the values are kept in the code list scheme

**Comment by ghobona** [comment]
As discussed with @rob-metalinkage and @estubkjaer , following the UI upgrade, this issue can now been closed.
