### ISSUE TITLE
Tile Matrix Set Register

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#49]
The [OGC Two Dimensional Tile Matrix Set (TMS)](http://docs.opengeospatial.org/is/17-083r2/17-083r2.html) standard provides some [Tile Matrix Set](http://docs.opengeospatial.org/is/17-083r2/17-083r2.html#61) definitions.

Other TMS definitions have been developed in Sprints, for example the April 2020 OGC API - Tiles sprint also created [one](https://github.com/opengeospatial/OGC-OS-Sprint-04-2020/blob/master/Shared_Datasets/tilematrixset-espg27700.json).

**Comment by ghobona** [comment]
The initial draft is now in the Incubation folder https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/tileMatrixSets/tms.csv

**Comment by ghobona** [comment]
@joanma747 Please review.

**Comment by jerstlouis** [comment]
@ghobona Could you please include GNOSISGlobalGrid in the registry?
H.2 in the TMS standard.

uri: http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad
prefLabel : GNOSISGlobalGrid
definition: World CRS84 Variable Width Global Grid TileMatrixSet definition
see also: http://docs.opengeospatial.org/is/17-083r2/17-083r2.html#106
tmsjson: http://schemas.opengis.net/tms/1.0/json/examples/GNOSISGlobalGrid.json

**Comment by ghobona** [comment]
Register added at http://www.opengis.net/def/tms/
