### ISSUE TITLE
Representation and publishing of Provisional URIs

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#50]
There is a suggestion to publish URIs as soon as they are proposed.

https://github.com/opengeospatial/NamingAuthority/issues/18#issuecomment-637178783

**Comment by rob-metalinkage** [comment]
In the upcoming upgrade of the HTML rendering will explore an option to trigger a styling change and inclusions based on property values in the displayed object - this will be configured to use a status property. 
Entailment regimes propagate status from concept schemes to concepts automatically.

**Comment by ghobona** [comment]
Closing this issue because Section 7.5 of the OGC-NA policy on definitions https://docs.opengeospatial.org/pol/09-048r5.html#_description allows us to use the **policy:status** predicate to indicate whether the resource is valid, retired, superseded, or under consideration.
