### ISSUE TITLE
Register GML 3.2 Simple Features media type profile

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#51]
From @rob-metalinkage 

looking at the OGCAPI docs there is a reference to profiles for media-types

application/gml+xml; version=3.2; profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0 

so a couple of questions here:
1) do we need to register profiles of media types?
2) should these be skos:narrrower relations to the overarching media type?
3) should media-type descriptions contain references to the specifications that define them?
4) should such profiles be "multi-purpose" - i.e. be the normative identifier of GML SF0 in this case, declared as a profile of GML

IMHO we need to start fleshing out these details to progress the definition server into an interface into a knowledge graph that helps users find related information easily.   This is an example where we want to stop multiple identifiers for gmlsf0 proliferating so its identiity can be used in various contexts, such as being able to get an overview of where it is being used, or whether two interfaces are interoperable at some level.

I have started on trying to link documents together, as we do not yet have a register of conformance classe URIs, and earlier specifications do not have a specific core conformance class identified separately

See GML SF0 http://www.opengis.net/def/docs/03-003r10

If the community can establish the actual requirements here I can start to build out tools so that the community knowledge can be captured - such as a way to suggest a relationship between two objects in the defs server

**Comment by cportele** [comment]
The URIs for the GML profiles were registered for the IANA registration of the gml+xml media type. Probably in 2016? At that time they resolved (as a stop gap to the GML-SF spec PDF document), but that seems to be no longer the case.

**Comment by cportele** [comment]
I also notice that the text in the original comment refers to a retired document (03-003r10).

GML Simple Feature Level 0 is specified by OGC document 10-100r3: by https://portal.ogc.org/files/?artifact_id=42729
