### ISSUE TITLE
Register GeoTIFF Tags in the OGC Definitions Server

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#68]
The GeoTIFF SWG recommends that the 6 GeoTIFF 1.1 (and 1.0) TIFF private tags defined in OGC GeoTIFF 1.1 (see http://docs.opengeospatial.org/is/19-008r4/19-008r4.html#_requirements_class_tiff) be added in the OGC Definitions Server under the control of OGC-NA and OAB

1. 33550   830E (Hex)          ModelPixelScaleTag Type Double (see 7.3.2. Requirements Class ModelPixelScaleTag)
2. 33922   8482 (Hex)          ModelTiepointTag Type Double (see 7.3.1. Requirements Class ModelTiepointTag)
3. 34264   85D8 (Hex)         ModelTransformationTag Type Double (see 7.3.3. Requirements Class ModelTransformationTag)
4. 34735   87AF (Hex)         GeoKeyDirectoryTag type SHORT (see 7.1.2. Requirements Class GeoKeyDirectoryTag
5. 34736   87B0 (Hex)         GeoDoubleParamsTag Type Double (see 7.1.5. Requirements Class GeoDoubleParamsTag)
6. 34737   87B1 (Hex)         GeoAsciiParamsTag type ASCII (see 7.1.6. Requirements Class GeoAsciiParamsTag

 
The OGC GeoTIFF 1.1 is at http://docs.opengeospatial.org/is/19-008r4/19-008r4.html

**Comment by EmDevys** [comment]
In order to fully document these GeoTIFF tags, the repeatability should be indicated as well, hoping OGC Def. server allows this. This results in the following specifications to be provided:
33550 830E (Hex) ModelPixelScaleTag Type Double (see 7.3.2. Requirements Class ModelPixelScaleTag) Count = 3
33922 8482 (Hex) ModelTiepointTag Type Double (see 7.3.1. Requirements Class ModelTiepointTag) Count  N = 6*K, with K = number of tiepoints
34264 85D8 (Hex) ModelTransformationTag Type Double (see 7.3.3. Requirements Class ModelTransformationTag) Count  16
34735 87AF (Hex) GeoKeyDirectoryTag type SHORT (see 7.1.2. Requirements Class GeoKeyDirectoryTag Count N >= 4
34736 87B0 (Hex) GeoDoubleParamsTag Type Double (see 7.1.5. Requirements Class GeoDoubleParamsTag) Count N
34737 87B1 (Hex) GeoAsciiParamsTag type ASCII (see 7.1.6. Requirements Class GeoAsciiParamsTag Count N

**Comment by ghobona** [comment]
@rob-metalinkage 

I have prepared the [SKOS-based content](https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/geotiff-tags). See the [turtle file](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/geotiff-tags/geotiff-tags.ttl). The next challenge is to try to express the characteristics such as Count and Type, as per the comment from @EmDevys .

Here's a suggested approach, using SHACL. Any objection/comments/modification? 

```ttl
prefix :       <http://example.org/> 
prefix sh:     <http://www.w3.org/ns/shacl#> 
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix schema: <http://schema.org/>
prefix foaf:   <http://xmlns.com/foaf/0.1/>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
        
<http://www.opengis.net/def/encoding/ogc/geotiff> a sh:NodeShape;
   sh:property [
    sh:path <http://www.opengis.net/def/geotiff-tag/ogc/1.1/33550> ; 
    sh:minCount 0; 
    sh:maxCount 3;
    sh:datatype xsd:double ;
  ]  .
```

**Comment by EmDevys** [comment]
Gobe, seems good to me in principle. I have 1 comment and 1 question:
- comment: for this tag, the mincount and maxCount are equal to 3, there must be exactly 3 double values.
- question: is foaf necessary for SHACL ? Otherwise I don't see it used in this example.

**Comment by ghobona** [comment]
@EmDevys 

Noted. I will ensure that the minCount and maxCount are equal to 3 for the tag.

Regarding foaf, it is not necessary. It just happened to be on the example I was using as a template. I will not include it in the actual register.

**Comment by EmDevys** [comment]
Great Gobe, sounds good to me then.

If there is no objection, I propose to move forward on this good basis. Good job ;))

Emmanuel

De : ghobona [mailto:notifications@github.com]
Envoyé : mercredi 17 février 2021 10:48
À : opengeospatial/NamingAuthority
Cc : Emmanuel Devys; Mention
Objet : Re: [opengeospatial/NamingAuthority] Register GeoTIFF Tags in the OGC Definitions Server (#68)


@EmDevys<https://github.com/EmDevys>

Noted. I will ensure that the minCount and maxCount are equal to 3 for the tag.

Regarding foaf, it is not necessary. It just happened to be on the example I was using as a template. I will not include it in the actual register.

**Comment by ghobona** [comment]
Thanks @EmDevys

**Comment by ghobona** [comment]
After reviewing SHACL further, we found that SHACL does not have the vocabulary to describe expressions such as "Count N = 6*K, with K = number of tiepoints".

So we will have to proceed with publishing the GeoTIFF tags register without those expressions. There is however a link to the relevant sections in the GeoTIFF specification, so a developer or end-user would be able to refer to the spec for details about minCount/maxCount.

**Comment by ghobona** [comment]
A Pull Request (PR https://github.com/opengeospatial/NamingAuthority/pull/98) has been created. The GeoTIFF Tags Register will be published on May 15th, 2021.

**Comment by ghobona** [comment]
Register published. PR closed.

https://github.com/opengeospatial/NamingAuthority/pull/98
