### ISSUE TITLE
Register data-meta relation type

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/NamingAuthority#69]
http://www.opengis.net/def/rel/ogc/1.0/data-meta Identifies general metadata for the context (dataset or collection) that is primarily intended for consumption by machines. 

API Common Issue 38.

**Comment by ghobona** [comment]
2021-03-22 OGC-NA meeting agreed to register this relation type.

**Comment by ghobona** [comment]
Published http://www.opengis.net/def/rel/ogc/1.0/data-meta
