### ISSUE TITLE
Adopt a policy that parameters should be in kebab-case

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#71]
There are different types of [case styles](https://medium.com/better-programming/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841).

The OGC API - Common SWG agreed to use kebab-case.

OGC API - Coverages SWG has agreed to use kebab-case.

The precedent is OGC API - Features - Part 2, which has been approved by the TC (i.e. `bbox-crs`).

EDR API currently uses lowerCamelCase. A ticket has been created for EDR API to be changed to kebab-case.

The OGC-NA has been asked to introduce policy requiring parameter names to be in kebab-case.

**Comment by ghobona** [comment]
Related discussion https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/170

**Comment by ghobona** [comment]
OGC API - Common SWG agreed on 2021-01-18 to include a Recommendation in OGC API - Common - Part 1: Core about using kebab-case.

**Comment by joanma747** [comment]
There is an agreement in OGC API Common to accept kababcase for query parameters.

**Comment by joanma747** [comment]
For path parameters it is more complicated, they are replaced by values that ARE NOT affected by this recommendation (or policy). Other "words" in the path such as "collections" or "tiles" etc. are also affected but it is unclear if the community agrees. In coverages "rangeSet" could be repladed by /range-set ?

**Comment by hylkevds** [comment]
That's annoying, it means implementers in quite a few languages (Java and JavaScript among them) can't use the same name for their variables as the name of the parameter.

**Comment by ghobona** [comment]
Closing this issue because a resolution was reached in OGC API - Common.
