### ISSUE TITLE
Resolvable OGC license URIs and vocab

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/NamingAuthority#74]
OGC licenses are used, or needed to be used, in places where then require a URI, for example, [the GeoSPARQL ontology](https://opengeospatial.github.io/ogc-geosparql/geosparql11/geo.ttl).

We have license deed files in repositories (see <https://github.com/opengeospatial/ogc-geosparql/blob/master/LICENSE> for GeoSPARQL) but no URIs for this content or even a list of OGC licenses.

Can we please have an OGC licenses vocab produced? Perhaps it could include OGC native licenses and general licenses recommended for use by OGC (e.g. CC licenses).

**Comment by ghobona** [comment]
Discussion taking place at https://github.com/opengeospatial/NamingAuthority/issues/86
