### ISSUE TITLE
Broken links on Defs Svr hompage

### ISSUE THREAD

**Issue by nicholascar** [opengeospatial/NamingAuthority#81]
The following links under "For More Information" are broken:

- Publishing Vocabularies via OGC Definitions Server
- Publishing Application Schema via OGC Definitions Server
- Publishing Interoperable Semantic Resource for Observations and Sensor Descriptions
- Interoperability of Semantic Resource Publishing Infrastructures

Looks like they are all pointing to the same, missing, GitHub repo.

**Comment by rob-metalinkage** [comment]
will need to update this tomorrow when Vocprez goes live... will make sure links are redirectable to current versions

**Comment by ghobona** [comment]
@rob-metalinkage The links are on the [About page](https://www.ogc.org/def-server).

**Comment by ghobona** [comment]
This issue is being addressed along with Issue https://github.com/opengeospatial/NamingAuthority/issues/137

A Trello ticket has been created.

**Comment by ghobona** [comment]
The page has been updated.
