### ISSUE TITLE
Redirection of URLs should be to http://www.opengis.net/def URLs

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#85]
Feedback from the Open OAB.

"I wish the defs server did not re-direct a URI to another URL, e.g. http://www.opengis.net/def/tilematrixset/OGC/1.0/UPSArcticWGS84Quad redirect to long URL with query parameter. This really makes it difficult to browse definitions and use or share URIs. Also wishing http://defs.opengis.net/ would return easy to browse definition categories."

"it would be great if you stay at the exact URI / URL."

**Comment by rob-metalinkage** [comment]
This is not possible with a http redirect, using recommended best practices and standard browser behaviour.

e.g. try https://wikipedia.org/wiki/Geography_Markup_Language

What we can do - and are planning - is to rearrange the display pages to make the correct URL citation process much more obvious and easy.  Currently its a rather minimal little arrow icon next to the URL (which is a local link to vocprez, which means external URIs that dont resolve can still offer useful information). 

The definitions categories is a separate issue - please create a separate issue for this.  What would these categories be?  There is already two layers - the home page  http://www.opengis.net/def with a list of all vocabularies and a "collections view" http://www.opengis.net/def/  - this needs some more thinking. Various UI improvements will explore better navigation now we have a technology for the UI we can control.
