### ISSUE TITLE
missing Content

### ISSUE THREAD

**Issue by marqh** [opengeospatial/NamingAuthority#87]
following changes to the naming authority service, the following URIs return an `Internal Server Error` (500), where these used to resolve:
https://www.opengis.net/def/binary-array-ld/Array
https://www.opengis.net/def/binary-array-ld/Container

indeed all Entities defined within:

https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/binary-array-ld/binary-array-ld.ttl

are returning 500 codes

**Comment by ghobona** [comment]
@marqh Thanks for spotting the issue. We are going to be re-populating the server shortly.

**Comment by rob-metalinkage** [comment]
Hi - yes there are two problems:

Need to talk to Kevin about the HTTPS redirects - the 500 error suggests these are broken - need to access server logs to find out why. Gobe - can you add Kevin to the available assignees and assign this first to him.

I also found there is a bug in the app schema publishing - i changed inferencing for SKOS to support VocPrez and something is nixing the output of the  inferencing for application schema.  I have a unit test running locally but need to dive deeper into configs to find out why new inferencing isnt being applied.

**Comment by rob-metalinkage** [comment]
only had option to close with comment - not comment..

**Comment by ghobona** [comment]
@rob-metalinkage 

I tried uploading the [binary-array-ld.ttl](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/binary-array-ld/binary-array-ld.ttl) as an app schema through the Django Admin app, however that did not work.

I then uploaded the triples directly to the RDF4JWorkbench instance. However, although they got uploaded successfully to RDF4JWorkbench instance, the triples are not discoverable through the VocPrez interface.

My guess is that VocPrez is configured to only search on `skos:Concept` and `skos:Collection` entries, and is ignoring `owl:Class` and other OWL types.

Any thoughts on a way forward?

**Comment by rob-metalinkage** [comment]
This is an entailment issue with some requirement for a piece of metadata VocPrez needs - I am investigating.

**Comment by rob-metalinkage** [comment]
I think I have fixed this - please check

**Comment by ghobona** [comment]
@rob-metalinkage 

It's working now. Thanks for the quick resolution.

@marqh I will create a separate GitHub issue to address the rendering of subClassOf resources of https://www.opengis.net/def/binary-array-ld/Container .
