### ISSUE TITLE
Register RDF representations of PipelineML

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#9]
The PipelineML SWG has requested for PipelineML code lists to be registered.

**Comment by rob-metalinkage** [comment]
Content is all in there already 

I have created a encompassing structure and loaded it so we can see it all

https://www.opengis.net/def/pipelineml/1.0/codelists/

**Comment by ghobona** [comment]
Great work!

Next: I've put in a request to the OGC Infrastructure Office for the PipelineML GML Dictionary files to be placed on the schemas repository. Once they have been uploaded, we will need a seeAlso predicate on the SKOS-encoded definitions to point to them. This is the approach we have used with previous codelists. In the future, we will move towards Content Negotiation.
