### ISSUE TITLE
Link Relations entries is not accessible after the recent upgrade

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#90]
After the upgrade of the User Interface (UI) to VocPrez, I reviewed all of the files in https://github.com/opengeospatial/NamingAuthority/tree/master/definitions/conceptschemes and found that none of the concepts listed in the following files can be accessed through the new user interface.

https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/linkrelations.ttl

The new instance does not appear to find the concepts, even though the concepts are available from the RDF4JWorkbench instance that is underneath.

For example, these URIs return an errors but should be returning concept descriptions:

* http://www.opengis.net/def/rel/iana/1.0/describedby
* http://www.opengis.net/def/rel/iana/1.0/next

**Comment by rob-metalinkage** [comment]
Republished via the CMS and the entailment functions and it seems to work now.  

PS - when publishing via CMS dont create a new ImportedConceptScheme when updating - update the existing one if it exist - should put in a check to stop this happening..
