### ISSUE TITLE
Character encoding of external resources and rendering of their labels

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/NamingAuthority#94]
The rendering of the names of the subClassOf resources at https://www.opengis.net/def/binary-array-ld/Container appears to show character encoding problems. This appears to affect external resources. 

![Screenshot 2021-04-19 at 13 48 39](https://user-images.githubusercontent.com/18121038/115238813-075fbf80-a116-11eb-984b-048927e62e49.png)

**Comment by rob-metalinkage** [comment]
Another fix avoided this - it was pulling in a wide range of multi-lingual labels from DCAT.  It now prefers the language of the current installation (english or none).  We may need to add explicit multilingual support.
